### ISSUE TITLE
Question about interaction with this module and Magento CE

### ISSUE THREAD

**Issue by beejhuff** [fballiano/magento-turpentine-recently-viewed#1]
This really isn't an issue to report as a bug on the repo...just a quesiton.

Fabrizio, are you aware of anyone using this with Magento CE?  CE doesn't have the built-in FPC that EE does, obviously, so I'm curious if this might be adapted to work with either a plug-in like [Lesti's FPC](https://github.com/GordonLesti/Lesti_Fpc)

**Comment by fballiano** [comment]
Varnish/turpentine works perfectly with CE, this module actually makes some calls to the customer segmentation which is available only in EE but it should be quite easy to patch (thus removing the dependancy from the Enterprise_CustomerSegment module).

I'll keep this issue open cause it seems a good idea to make this module available also for EE out of the box.

About Lesti's I really have no idea, it would need a complete rewrite and would be a completely different module (I don't even know if that module has the "bug", I never worked with that).
